# Generated by Django 5.0.1 on 2024-01-04 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acesso_ssh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidade',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acesso_ssh.empresa'),
        ),
    ]
