# Generated by Django 5.0.1 on 2024-01-04 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acesso_ssh', '0002_localidade_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaArp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('arp', models.TextField(blank=True, null=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acesso_ssh.ativoenel')),
            ],
        ),
    ]
