# Generated by Django 4.2.9 on 2024-01-08 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acesso_ssh', '0004_alter_tabelaarp_options_tabelaarp_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabelaarp',
            old_name='arp',
            new_name='comando',
        ),
    ]
